"""Initial migration

Revision ID: dc97434e21a4
Revises: 
Create Date: 2026-08-15 21:18:34.895014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc97434e21a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('twin_status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('exposure', sa.String(length=50), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_controls',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('risk_reduction', sa.Integer(), nullable=False),
    sa.Column('affected_assets', sa.JSON(), nullable=True),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('mfa', sa.String(length=20), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_assets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('storage_asset_id', sa.String(length=50), nullable=False),
    sa.Column('storage_name', sa.String(length=100), nullable=False),
    sa.Column('exposure', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['storage_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('security', sa.String(length=50), nullable=False),
    sa.Column('last_seen', sa.String(length=50), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('ml_user_risks',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('additional_control_id', sa.String(length=50), nullable=False),
    sa.Column('is_counterfactual', sa.Boolean(), nullable=False),
    sa.Column('parent_simulation_id', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('blast_radius', sa.Integer(), nullable=False),
    sa.Column('critical_assets', sa.Integer(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('blocked_at', sa.String(length=100), nullable=True),
    sa.Column('path_json', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['additional_control_id'], ['security_controls.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockchain_evidence',
    sa.Column('simulation_id', sa.String(length=50), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('integrity', sa.String(length=20), nullable=False),
    sa.Column('hash', sa.String(length=100), nullable=False),
    sa.Column('ledger', sa.String(length=20), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockchain_evidence')
    op.drop_table('simulations')
    op.drop_table('ml_user_risks')
    op.drop_table('devices')
    op.drop_table('data_assets')
    op.drop_table('users')
    op.drop_table('security_controls')
    op.drop_table('assets')
    op.drop_table('security_events')
    op.drop_table('organizations')
    # ### end Alembic commands ###
